- name: Run nginx in docker container with ansible
  hosts: localhost
  become: false
  vars:
    volume_name: db-data
  tasks:
    - name: Pull nginx image
      community.docker.docker_image:
        name: nginx
        tag: latest
        source: pull

    - name: create docker volume
      community.docker.docker_volume:
        name: "{{ volume_name }}"
        state: present
      register: volume_result

    - name: Create custom network
      community.docker.docker_network:
        name: nginx-ansible-network
        state: present
        driver: bridge                  

    - name: Run nginx container
      community.docker.docker_container:
        name: nginx-demo
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "8080:80"
        volumes:
          - "{{ playbook_dir }}/html:/usr/share/nginx/html"
          - "{{ volume_name }}:/usr/share/nginx/data"
        networks:
          - name: nginx-ansible-network
        env:
          DB_HOST: "db"
        command: sh -c "echo $DB_HOST"