services:
  backend:
    environment:
      # מדליק את מצב הדיבאג כדי לראות לוגים מפורטים
      LOG_LEVEL: debug
      FLASK_DEBUG: 1

  worker:
    environment:
      # מדליק פירוט לוגים גם לוורקר
      LOG_LEVEL: debug
      # משתנה סביבה ייעודי שספריית boto3 מזהה לדיבאג של בקשות AWS
      BOTO_LOG_LEVEL: debug