- name: deploy nginx
  hosts: web
  become: true

  tasks:
    - name: install nginx
      ansible.builtin.package:
          name: nginx
          state: present
     
    - name: Ensure nginx web root exists
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Deploy custom index page
      ansible.builtin.template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: "0644"

    - name: Ensure nginx is running 
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    